// Generated by ego.
// DO NOT EDIT

package model
import (
"fmt"
"io"
"strings"
"github.com/boourns/scaffold/ast"
"github.com/boourns/scaffold/util"
"github.com/boourns/scaffold/sqlgen"
)
var _ = fmt.Sprint("") // just so that we can keep the fmt import for now
//line model.go.ego:1
 func modelTemplate(w io.Writer, m *ast.Model) error  {
//line model.go.ego:2
_, _ = io.WriteString(w, "\n\n")
//line model.go.ego:9
_, _ = io.WriteString(w, "\n\npackage ")
//line model.go.ego:10
_, _ = fmt.Fprintf(w, "%v",  strings.ToLower(m.Name) )
//line model.go.ego:11
_, _ = io.WriteString(w, "\n\nimport (\n\t\"github.com/boourns/dbutil\"\n  \"database/sql\"\n  \"fmt\"\n)\n\nfunc sqlFieldsFor")
//line model.go.ego:18
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:18
_, _ = io.WriteString(w, "() string {\n  return \"")
//line model.go.ego:19
_, _ = fmt.Fprintf(w, "%v",  util.StringJoin(m.FieldSlice(), ", ") )
//line model.go.ego:19
_, _ = io.WriteString(w, "\"\n}\n\nfunc load")
//line model.go.ego:22
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:22
_, _ = io.WriteString(w, "(rows *sql.Rows) (*")
//line model.go.ego:22
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:22
_, _ = io.WriteString(w, ", error) {\n\tret := ")
//line model.go.ego:23
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:23
_, _ = io.WriteString(w, "{}\n\n\terr := rows.Scan(")
//line model.go.ego:25
_, _ = fmt.Fprintf(w, "%v",  fieldString("&ret.", m.FieldSlice(), "") )
//line model.go.ego:25
_, _ = io.WriteString(w, ")\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn &ret, nil\n}\n\nfunc Select(tx dbutil.DBLike, cond string, condFields ...interface{}) ([]*")
//line model.go.ego:32
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:32
_, _ = io.WriteString(w, ", error) {\n  ret := []*")
//line model.go.ego:33
_, _ = fmt.Fprintf(w, "%v", m.Name)
//line model.go.ego:33
_, _ = io.WriteString(w, "{}\n  sql := fmt.Sprintf(\"SELECT %s from ")
//line model.go.ego:34
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:34
_, _ = io.WriteString(w, " %s\", sqlFieldsFor")
//line model.go.ego:34
_, _ = fmt.Fprintf(w, "%v", m.Name)
//line model.go.ego:34
_, _ = io.WriteString(w, "(), cond)\n\trows, err := tx.Query(sql, condFields...)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tfor rows.Next() {\n    item, err := load")
//line model.go.ego:40
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:40
_, _ = io.WriteString(w, "(rows)\n    if err != nil {\n      return nil, err\n    }\n    ret = append(ret, item)\n  }\n  rows.Close()\n  return ret, nil\n}\n\nfunc (s *")
//line model.go.ego:50
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:50
_, _ = io.WriteString(w, ") Update(tx dbutil.DBLike) error {\n\t\tstmt, err := tx.Prepare(fmt.Sprintf(\"UPDATE ")
//line model.go.ego:51
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:51
_, _ = io.WriteString(w, "(%s) VALUES(")
//line model.go.ego:51
_, _ = fmt.Fprintf(w, "%v",  util.QuestionMarks(len(m.FieldSlice())) )
//line model.go.ego:51
_, _ = io.WriteString(w, ") WHERE ")
//line model.go.ego:51
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:51
_, _ = io.WriteString(w, ".ID = ?\", sqlFieldsFor")
//line model.go.ego:51
_, _ = fmt.Fprintf(w, "%v", m.Name)
//line model.go.ego:51
_, _ = io.WriteString(w, "()))\n\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n\n    params := []interface{}{")
//line model.go.ego:57
_, _ = fmt.Fprintf(w, "%v",  fieldString("s.", m.FieldSlice(), "") )
//line model.go.ego:57
_, _ = io.WriteString(w, "}\n    params = append(params, s.ID)\n\n\t\t_, err = stmt.Exec(params...)\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n\n    return nil\n}\n\nfunc (s *")
//line model.go.ego:68
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:68
_, _ = io.WriteString(w, ") Insert(tx dbutil.DBLike) error {\n\t\tstmt, err := tx.Prepare(\"INSERT INTO ")
//line model.go.ego:69
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:69
_, _ = io.WriteString(w, "(")
//line model.go.ego:69
_, _ = fmt.Fprintf(w, "%v",  fieldString("", m.FieldSliceWithoutID(), "") )
//line model.go.ego:69
_, _ = io.WriteString(w, ") VALUES(")
//line model.go.ego:69
_, _ = fmt.Fprintf(w, "%v",  util.QuestionMarks(len(m.FieldSliceWithoutID())) )
//line model.go.ego:69
_, _ = io.WriteString(w, ")\")\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n\n\t\t_, err = stmt.Exec(")
//line model.go.ego:74
_, _ = fmt.Fprintf(w, "%v",  fieldString("s.", m.FieldSliceWithoutID(), "") )
//line model.go.ego:74
_, _ = io.WriteString(w, ")\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n\t  return nil\n}\n\nfunc Create")
//line model.go.ego:81
_, _ = fmt.Fprintf(w, "%v",  m.Name )
//line model.go.ego:81
_, _ = io.WriteString(w, "Table(tx dbutil.DBLike) error {\n\t\tstmt, err := tx.Prepare(`")
//line model.go.ego:82
_, _ = fmt.Fprintf(w, "%v",  sqlgen.CreateTable(m) )
//line model.go.ego:82
_, _ = io.WriteString(w, "`)\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n\n\t\t_, err = stmt.Exec()\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n\t  return nil\n}\n")
return nil
}
