// Generated by ego.
// DO NOT EDIT

//line model.ts.ego:1

package model

import "fmt"
import "html"
import "io"
import "context"

import (
	"github.com/boourns/scaffold/ast"
	"strings"
	//"github.com/boourns/scaffold/util"
	//"github.com/boourns/scaffold/sqlgen"
	//"fmt"
)

//arrays and slices aren't handled properly.
func tsTypeForField(f ast.Field) string {
	switch f.Type {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte", "rune", "float32", "float64":
		return "number"
	case "string":
		return "string"
	case "bool":
		return "boolean"
	default:
		return "any" //🤷‍♂️
	}
}

func fieldNameString(m *ast.Model) string {
	return strings.Join(m.FieldSlice(), ",")
}

func modelTemplateTS(w io.Writer, m *ast.Model) {

//line model.ts.ego:32
	_, _ = io.WriteString(w, "\nclass ")
//line model.ts.ego:32
	_, _ = fmt.Fprint(w, m.Name)
//line model.ts.ego:32
	_, _ = io.WriteString(w, " {\n    ")
//line model.ts.ego:33
	for _, field := range m.Fields {
//line model.ts.ego:34
		_, _ = io.WriteString(w, "\n    ")
//line model.ts.ego:34
		_, _ = fmt.Fprint(w, field.Name)
//line model.ts.ego:34
		_, _ = io.WriteString(w, ": ")
//line model.ts.ego:34
		_, _ = fmt.Fprint(w, tsTypeForField(field))
//line model.ts.ego:34
		_, _ = io.WriteString(w, " | undefined\n    ")
//line model.ts.ego:35
	}
//line model.ts.ego:36
	_, _ = io.WriteString(w, "\n    SelectAll: string = \"SELECT (")
//line model.ts.ego:36
	_, _ = fmt.Fprint(w, fieldNameString(m))
//line model.ts.ego:36
	_, _ = io.WriteString(w, ") FROM ")
//line model.ts.ego:36
	_, _ = fmt.Fprint(w, m.Name)
//line model.ts.ego:36
	_, _ = io.WriteString(w, "\"\n    SelectByID: string = \"SELECT (")
//line model.ts.ego:37
	_, _ = fmt.Fprint(w, fieldNameString(m))
//line model.ts.ego:37
	_, _ = io.WriteString(w, ") FROM ")
//line model.ts.ego:37
	_, _ = fmt.Fprint(w, m.Name)
//line model.ts.ego:37
	_, _ = io.WriteString(w, " WHERE ID=?\"\n}\nexport default ")
//line model.ts.ego:39
	_, _ = fmt.Fprint(w, m.Name)
//line model.ts.ego:40
	_, _ = io.WriteString(w, "\n")
//line model.ts.ego:40
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
