#!/bin/bash

set -e

ego

pushd ../cmd/scaffold/
go build
popd

../cmd/scaffold/scaffold -in="test/user.go" -out="test/user_model.go" -struct="User" -scaffold="model"

pushd test
go get
go test
popd

