#!/bin/bash

set -e

if [ ! -f ../cmd/scaffold/scaffold ]; then
  pushd ../cmd/scaffold/
  go build
  popd
fi

../cmd/scaffold/scaffold -in="test/user.go" -out="test/user_model.go" -struct="User" -scaffold="model"

pushd test
go get
go test
popd

